---
title: "calendar_proposal_template"
author: "BilalTariq"
format: pdf
editor: visual
---

# Calendar Query Proposal

```{=html}
<!--
This is a recap from the assignment. 

Identify 2-4 primary questions of interest to you about how you spend your time. Your questions should address something meaningful to you, but **be sure you identify questions you feel comfortable sharing with me** (your reports will not be shared with the class) and that they are feasible for the 14-day data collection period. 

Feel free to expand upon the basic question of "Where does my time go?" or "How do I spend my time?" or explore a variation of it. Some other ideas include but are not limited to:

* Document *intended time* doing things (e.g. studying, sleeping) versus *actual time* doing those things, and compare results

* Document time spent on each course, and/or time spent on different parts of a course (e.g. in class, reading, homework, etc.)

* Document time spent on school vs. work vs. leisure vs. rest, etc.

* If you already use a calendar app as a way to keep track of your schedule, you could compare how your time was spent last year at this time versus how your time is being spent this semester.

Note: You are not bound to the ideas you record here.  The visualizations and table can change before your final submission.  However, I want to make sure your plan aligns with your questions, that your project is manageable, and that you're on the right track (i.e. that you'll end up with data that lets you do something meaningful).
-->
```
## What questions are you planning to focus on?

I am planning on focusing on time spent on courses vs. work vs. sleep. In this scenario, I want to see how the major 3 activities of my day actually go by.

## Describe two visualizations (type of plot, coordinates, visual cues, etc.) you imagine creating that help address your questions of interest.

I would use a boxplot visualisation to see the average and the quartiles of the amount of hours I spend on these activities. I would use different colors to show the different boxplots (alternatively, I may just consider generating 3 boxplots for each of the categories). Furthermore, I would use a bar graph to compare the total number of hours in the two weeks spent on these activities.

## Describe one table you imagine creating that helps address your questions of interest (what summary statistics will you present? what will the rows be? what will the columns be?).

I imagine creating a table for the boxplots where in the rows we would have the different activities and in the columns we will have the mean, median, mode, interquartile ranges and total time spent on these activities.

<!-- Remember the visuals and table should convey different information. -->

## Do you have any questions for me as we get started with this project?
